// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnjmnxvzeqscuatjtuua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imduam1ueHZ6ZXFzY3VhdGp0dXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NzYwMDgsImV4cCI6MjA3NzA1MjAwOH0.I_TvkM0lsWM3vH4PXopoXAKHWu4-RjgyEFgNwCFAUVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Regular client (anon key) - for normal operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});